const express = require('express');
const router = express.Router();
const Student = require('../models/Student');
const { auth, studentAuth } = require('../middleware/auth');
const upload = require('../config/multer');

/**
 * Student Routes
 * Handles student-specific actions like profile updates and document uploads.
 * All routes here are protected and require a valid student token.
 */

// 1. Get Profile
// Fetches the logged-in student's full data from the DB, excluding the password hash.
router.get('/profile', [auth, studentAuth], async (req, res) => {
    try {
        const student = await Student.findById(req.user.id).select('-password');
        if (!student) return res.status(404).json({ message: 'Student profile not found in database.' });
        res.json(student);
    } catch (err) {
        console.error('Profile Fetch Error:', err.message);
        res.status(500).send('Server Error');
    }
});

// 2. Update Details
// Updates personal, guardian, academic, and category details for the student.
router.put('/update', [auth, studentAuth], async (req, res) => {
    const { personalDetails, guardianDetails, academicDetails, category, branch } = req.body;
    try {
        let student = await Student.findById(req.user.id);
        if (!student) return res.status(404).json({ message: 'Student not found. Please re-register.' });

        // Update fields only if they are provided in the request body
        if (personalDetails) student.personalDetails = personalDetails;
        if (guardianDetails) student.guardianDetails = guardianDetails;
        if (academicDetails) student.academicDetails = academicDetails;
        if (category) student.category = category;
        if (branch) student.branch = branch;

        await student.save();
        res.json(student);
    } catch (err) {
        console.error('Student Update Error:', err.message);
        res.status(500).json({ message: 'Failed to update student profile', error: err.message });
    }
});

// 3. Document Upload
// Handles file uploads (PDF/Images) and saves the local path into the student's document list.
router.post('/upload', [auth, studentAuth], upload.single('document'), async (req, res) => {
    try {
        if (!req.file) return res.status(400).json({ message: 'Please upload a file' });

        const student = await Student.findById(req.user.id);
        if (!student) return res.status(404).json({ message: 'Student not found' });

        // Create a new document entry with the unique filename generated by Multer
        const newDoc = {
            name: req.body.name || req.file.originalname,
            url: `/uploads/${req.file.filename}`, // Web-accessible link to the file
            status: 'Pending'                    // Initially set to pending until admin reviews
        };

        student.documents.push(newDoc);
        await student.save();

        res.json(student);
    } catch (err) {
        console.error('Upload Error:', err.message);
        res.status(500).send('Server Error');
    }
});

module.exports = router;

